import '../../../../domain/models.dart';

/// Static list of municipalities + barangays for Davao del Sur, used by the
/// worker onboarding "Personal Info" step's address picker.
///
/// Sourced from the Philippine Standard Geographic Code (PSGC). The split
/// from Davao Occidental (2013) is reflected: only the 9 municipalities and
/// 1 city that remain in Davao del Sur are listed.
class DavaoDelSur {
  const DavaoDelSur._();

  static const String province = 'Davao del Sur';

  static const List<String> municipalities = <String>[
    'Bansalan',
    'Digos City',
    'Hagonoy',
    'Kiblawan',
    'Magsaysay',
    'Malalag',
    'Matanao',
    'Padada',
    'Santa Cruz',
    'Sulop',
  ];

  static const Map<String, List<String>> barangays = <String, List<String>>{
    'Bansalan': <String>[
      'Alegre',
      'Anonang',
      'Bitaug',
      'Bonifacio',
      'Buenavista',
      'Darapuay',
      'Dolo',
      'Eden',
      'Kinuskusan',
      'Libertad',
      'Linawan',
      'Mabuhay',
      'Mabunga',
      'Managa',
      'Marber',
      'New Clarin',
      'Poblacion',
      'Polo Pequeño',
      'Rizal',
      'Santo Niño',
      'Sibayan',
      'Tinongtongan',
      'Tubod',
      'Union',
    ],
    'Digos City': <String>[
      'Aplaya',
      'Balabag',
      'Binaton',
      'Cogon',
      'Colorado',
      'Dawis',
      'Dulangan',
      'Goma',
      'Igpit',
      'Kapatagan',
      'Kiagot',
      'Lungag',
      'Mahayahay',
      'Matti',
      'Ruparan',
      'San Agustin',
      'San Jose',
      'San Miguel',
      'San Roque',
      'Sinawilan',
      'Soong',
      'Tiguman',
      'Tres de Mayo',
      'Zone 1 (Pob.)',
      'Zone 2 (Pob.)',
      'Zone 3 (Pob.)',
    ],
    'Hagonoy': <String>[
      'Aplaya',
      'Balutakay',
      'Clib',
      'Guihing Aplaya',
      'Guihing Proper',
      'Hagonoy Crossing',
      'Kibuaya',
      'Lanuro',
      'Lapulabao',
      'Leling',
      'Mahayahay',
      'Maliit Digos',
      'New Quezon',
      'Paligue',
      'Poblacion',
      'Sacub',
      'San Guillermo',
      'San Isidro',
      'Sinayawan',
      'Tologan',
    ],
    'Kiblawan': <String>[
      'Abnate',
      'Bagong Negros',
      'Bagong Silang',
      'Bagumbayan',
      'Balasiao',
      'Bonifacio',
      'Bulol-Salo',
      'Bunot',
      'Cogon-Bacaca',
      'Dapok',
      'Ihan',
      'Kibongbong',
      'Kimlawis',
      'Kisulan',
      'Lati-an',
      'Manuel Guianga',
      'Maraga-a',
      'Molopolo',
      'New Sibonga',
      'Panaglib',
      'Pasig',
      'Poblacion',
      'San Isidro',
      'San Pedro',
      'Santo Niño',
      'Tacub',
      'Tacul',
      'Tibongbong',
    ],
    'Magsaysay': <String>[
      'Asbang',
      'Bacungan',
      'Balnate',
      'Bao',
      'Blocon',
      'Calumpang',
      'Dalumay',
      'Glamang',
      'Kanapulo',
      'Kasuga',
      'Lower Bala',
      'Malawanit',
      'Malongon',
      'New Ilocos',
      'New Opon',
      'Poblacion',
      'San Isidro',
      'San Miguel',
      'Tagaytay',
      'Tomiawes',
      'Upper Bala',
    ],
    'Malalag': <String>[
      'Bagumbayan',
      'Baybay',
      'Bolton',
      'Bukid',
      'Caputian',
      'Ibo',
      'Kiblagon',
      'Lapla',
      'Lower Mainit',
      'Mabini',
      'New Baclayon',
      'New Buhi',
      'Parame',
      'Pitu',
      'Poblacion',
      'Rizal',
      'San Isidro',
      'San Miguel',
      'Tagansule',
      'Tagaytay',
      'Upper Mainit',
    ],
    'Matanao': <String>[
      'Asbang',
      'Asinan',
      'Bagumbayan',
      'Bangkal',
      'Bantakan',
      'Buas',
      'Buri',
      'Cabligan',
      'Camanchiles',
      'Colonsabak',
      'Dongan-Pekong',
      'Kabasagan',
      'Kapok',
      'Kauswagan',
      'Kibao',
      'Kibongbong',
      'Langa-an',
      'Mabini',
      'Manga',
      'New Katipunan',
      'New Murcia',
      'New Visayas',
      'Poblacion',
      'Saboy',
      'San Jose',
      'San Miguel',
      'San Vicente',
      'Sinaragan',
      'Sinawilan',
      'Tamlangon',
      'Tibongbong',
      'Towak',
    ],
    'Padada': <String>[
      'Almendras (Pob.)',
      'Don Sergio Osmeña Sr.',
      'Harada Butai',
      'Lower Katipunan',
      'Lower Limonzo',
      'Lower Malinao',
      'Maganay',
      'N.C. Ordaneza District (Pob.)',
      'Noli Cantillas',
      'Palili',
      'Paligue',
      'Piape',
      'Punta Piape',
      'Quirino District (Pob.)',
      'Rizal District (Pob.)',
      'San Isidro',
      'Tulogan',
      'Upper Limonzo',
      'Upper Malinao',
    ],
    'Santa Cruz': <String>[
      'Astorga',
      'Bato',
      'Coronon',
      'Darong',
      'Inawayan',
      'Jose Rizal',
      'Matutungan',
      'Melilia',
      'Pilan',
      'San Lorenzo Ruiz',
      'San Pedro',
      'San Roque',
      'Saparon',
      'Sibulan',
      'Tagabuli',
      'Tibolo',
      'Tuban',
      'Zone I (Pob.)',
      'Zone II (Pob.)',
      'Zone III (Pob.)',
    ],
    'Sulop': <String>[
      'Balasiao',
      'Buguis',
      'Carre',
      'Clib',
      'Harada Butai',
      'Katipunan',
      'Kiblagon',
      'Labon',
      'Laperas',
      'Lapla',
      'Litos',
      'Luparan',
      'McKinley',
      'New Cebu',
      'Osmeña',
      'Palili',
      'Parame',
      'Poblacion',
      'Roxas',
      'Solongvale',
      'Tagolilong',
      'Tala-o',
      'Talas',
      'Tanwalang',
      'Waterfall',
    ],
  };

  /// Composes a printable address string from the three picker fields.
  static String formatAddress({
    required String? barangay,
    required String? municipality,
  }) {
    final parts = <String>[
      if (barangay != null && barangay.isNotEmpty) barangay,
      if (municipality != null && municipality.isNotEmpty) municipality,
      province,
    ];
    return parts.join(', ');
  }

  /// Approximate WGS84 center for each [municipalities] entry (town/city hall
  /// area). Used for commute distance when device GPS is unreliable.
  static const Map<String, GeoPoint> _municipalityCenters = {
    'bansalan': GeoPoint(lat: 6.7864, lng: 125.1956),
    'digos city': GeoPoint(lat: 6.7461, lng: 125.3553),
    'hagonoy': GeoPoint(lat: 6.6842, lng: 125.2895),
    'kiblawan': GeoPoint(lat: 6.6111, lng: 125.2386),
    'magsaysay': GeoPoint(lat: 6.7667, lng: 125.1667),
    'malalag': GeoPoint(lat: 6.6050, lng: 125.4019),
    'matanao': GeoPoint(lat: 6.7496, lng: 125.2215),
    'padada': GeoPoint(lat: 6.6389, lng: 125.6172),
    'santa cruz': GeoPoint(lat: 6.8367, lng: 125.4147),
    'sulop': GeoPoint(lat: 6.5986, lng: 125.3436),
  };

  /// [rawName] should match a label from [municipalities] (e.g. `Padada`,
  /// `Digos City`). Returns null if unknown.
  static GeoPoint? approxCenterForMunicipality(String? rawName) {
    if (rawName == null) return null;
    var k = rawName.trim().toLowerCase();
    if (k.isEmpty) return null;
    if (k == 'digos') k = 'digos city';
    return _municipalityCenters[k];
  }
}
